Big evolution

diff --git a/board/edufw/rootfs-overlay/sbin/edufw_firmware_upgrade b/board/edufw/rootfs-overlay/sbin/edufw_firmware_upgrade
--- a/board/edufw/rootfs-overlay/sbin/edufw_firmware_upgrade
+++ b/board/edufw/rootfs-overlay/sbin/edufw_firmware_upgrade
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Args : firmawre_name firmware_url firmware_sha256
 FW_NAME="$1"
@@ -14,12 +14,17 @@ FIRMWARE_DIR="$EDUFW_MP/firmwares"
 
 # Create destination directory
 mkdir -p "$FIRMWARE_DIR"
-TMPFILE=$(tempfile -p "FIRMWARE" -d "$FIRMWARE_DIR")
+TMPFILE=$(mktemp -p "$FIRMWARE_DIR")
 
 # Downloading firmware to temporary file
 echo "Downloading $FW_NAME"
-wget -o "$TMPFILE" "$FW_URL" \
+wget -O "$TMPFILE" "$FW_URL" \
   || die "Cannot download $FW_URL to $TMPFILE"
+
+echo "Checking file integrity"
+CALC_SHA256=$(sha256sum "$TMPFILE" | cut -d" " -f1)
+[ "$CALC_SHA256" == "$FW_SHA256" ] \
+  || die "File integrity ERROR ($CALC_SHA256 instead of $FW_SHA256)"
 
 # Backup old firmware
 echo "Backup old firmware"
@@ -27,7 +32,7 @@ cp -a "$EDUFW_FIRMWARE" "$EDUFW_FIRMWARE.old" \
   || die "Cannot backup old firmware"
 
 # Move firmare to standard destination
-if mv $TMPFILE "$EDUFW_FIRMWARE" then
+if mv $TMPFILE "$EDUFW_FIRMWARE"; then
   # Remove firmware validation
   rm "$EDUFW_FIRMWARE.ok"
 
diff --git a/board/edufw/rootfs-overlay/sbin/edufw_getcert b/board/edufw/rootfs-overlay/sbin/edufw_getcert
--- a/board/edufw/rootfs-overlay/sbin/edufw_getcert
+++ b/board/edufw/rootfs-overlay/sbin/edufw_getcert
@@ -7,7 +7,7 @@
 
 WGET="wget"
 
-EDUFW_CA_DIR=$(get_config_file "ca")
+EDUFW_CA=$(get_config_file "ca.pem")
 REG_SERVER_FILE=$(get_config_file ".regserver.txt")
 REGID_FILE=$(get_config_file "regid.conf")
 CERT_FILE=$(get_config_file "cert.pem")
@@ -26,11 +26,24 @@ if [ -s "$REGID_FILE" ]; then
     fi
 fi
 
-"$WGET" --ca-directory="$EDUFW_CA_DIR" -q -O"$CERT_FILE" --post-data="regid=$regid" "$REG_SERVER/get-cert/"
+if [ -s "$CERT_FILE" ]; then
+    echo "Certificate already downloaded" >&2
+    exit 0
+fi
+
+"$WGET" --ca-certificate="$EDUFW_CA" -q -O"$CERT_FILE" --post-data="regid=$regid" "$REG_SERVER/get-cert/"
 RES="$?"
 
 while [ "$RES" != 0 ]; do
     sleep 60
-    "$WGET" --ca-directory="$EDUFW_CA_DIR" -q -O"$CERT_FILE" --post-data="regid=$regid" "$REG_SERVER/get-cert/"
+    "$WGET" --ca-certificate="$EDUFW_CA" -q -O"$CERT_FILE" --post-data="regid=$regid" "$REG_SERVER/get-cert/"
     RES="$?"
 done
+
+if cp "$CERT_FILE" "/edufw/config/edufw/cert.pem"; then
+  :
+else
+  echo "ERROR: Cannot copy registration id file '$CERT_FILE' to '/edufw/config/edufw/cert.pem'" >&2
+  exit 3
+fi
+
diff --git a/board/edufw/rootfs-overlay/sbin/edufw_register b/board/edufw/rootfs-overlay/sbin/edufw_register
--- a/board/edufw/rootfs-overlay/sbin/edufw_register
+++ b/board/edufw/rootfs-overlay/sbin/edufw_register
@@ -10,9 +10,9 @@ WGET="wget"
 MAXDAYS="7"
 
 REG_SERVER_FILE=$(get_config_file ".regserver.txt")
-REGID_FILE=$(get_config_file "regid.conf")
 PASS_FILE=$(get_config_file ".regpass.txt")
-EDUFW_CA_DIR=$(get_config_file "ca")
+EDUFW_CA=$(get_config_file "ca.pem")
+REGID_FILE=$(get_config_file "regid.conf")
 KEY_FILE=$(get_config_file "cert.key")
 REQ_FILE="/tmp/cert.req"
 
@@ -39,10 +39,10 @@ MAC=$(ip ad sh dev "$DEVICE" | grep /ether | awk '{print $2}')
 if [ -z "$MAC" ]; then MAC=00:00:00:00:00:00; fi
 PASS=$(cat "$PASS_FILE")
 
-URLENCODED_MAC=`urlencode "$MAC"`
-URLENCODED_PASS=`urlencode "$PASS"`
+URLENCODED_MAC=`perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$MAC"`
+URLENCODED_PASS=`perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$PASS"`
 
-if "$WGET" --ca-directory="$EDUFW_CA_DIR" -O"$REGID_FILE" --post-data="mac=$URLENCODED_MAC&pass=$URLENCODED_PASS" "$REG_SERVER/register/"; then
+if "$WGET" --ca-certificate="$EDUFW_CA" -O"$REGID_FILE" --post-data="mac=$URLENCODED_MAC&pass=$URLENCODED_PASS" "$REG_SERVER/register/"; then
 . "$REGID_FILE"
 else
   echo "ERROR: Cannot request registration id" >&2 
@@ -51,8 +51,22 @@ fi
 
 if openssl req -newkey rsa:"$RSA_BITS" -keyout "$KEY_FILE" -out "$REQ_FILE" -nodes -subj "/CN=$regid/" 2>/dev/null; then
   URLENCODED_REQ="$(perl -MURI::Escape -e 'print uri_escape(do { local $/; <STDIN> });' <$REQ_FILE)"
-  "$WGET" --ca-directory="$EDUFW_CA_DIR" -q -Orequest.res --post-data="req=$URLENCODED_REQ" "$REG_SERVER/set-request/$regid/"
+  "$WGET" --ca-certificate="$EDUFW_CA" -q -Orequest.res --post-data="req=$URLENCODED_REQ" "$REG_SERVER/set-request/$regid/"
 else
   echo "ERROR: Cannot create certificate request" >&2 
   exit 2
+fi
+
+if cp "$REGID_FILE" "/edufw/config/edufw/regid.conf"; then
+  :
+else
+  echo "ERROR: Cannot copy registration id file '$REGID_FILE' to '/edufw/config/edufw/regid.conf'" >&2
+  exit 3
+fi
+
+if cp "$KEY_FILE" "/edufw/config/edufw/cert.key"; then
+  :
+else
+  echo "ERROR: Cannot copy registration id file '$KEY_FILE' to '/edufw/config/edufw/cert.key'" >&2
+  exit 4
 fi
